### ISSUE TITLE
Duplicate rows unexpectedly when switching between documents in the same database

### ISSUE THREAD

**Issue by MrWillCom** [RenzHoly/Mongood#64]
I'm testing it by the development server.

I have a database with 2 documents. One includes 2 rows, one includes 1 row. It automatically duplicate  rows when I switch between 2 documents almost randomly.

**Comment by MrWillCom** [comment]
[Here](https://github.com/RenzHoly/Mongood/files/5011925/zipped.zip) is the record.

**Comment by RenzHoly** [comment]
Are you sure you are using the latest code?
I tried and it's ok

**Comment by RenzHoly** [comment]
Record is [Here](https://github.com/RenzHoly/Mongood/files/5021764/mongood.mp4.zip)

**Comment by MrWillCom** [comment]
I've fetched your repository recently and tested it again, but this bug still occurs here.

**Comment by RenzHoly** [comment]
That is weird. Did you re-build with `npm run build`?

**Comment by MrWillCom** [comment]
> That is weird. Did you re-build with `npm run build`?

No, I used `npm run dev` and `go run main.go headless.go`.

**Comment by RenzHoly** [comment]
> > That is weird. Did you re-build with `npm run build`?
> 
> No, I used `npm run dev` and `go run main.go headless.go`.
> 
> Before this, I removed `node_modules/` and ran `npm i`.

That's ok.
I'm using Chrome on MacOS. I'll check this problem with Edge on Windows later.

**Comment by RenzHoly** [comment]
But I don't think it is caused by different browser

**Comment by MrWillCom** [comment]
> But I don't think it is caused by different browser

Maybe, I've tested it on Windows with [Microsoft Edge (Chromium)](https://www.microsoft.com/en-us/edge), Chrome and Firefox.

**Comment by RenzHoly** [comment]
I released client package, you can try it: https://github.com/RenzHoly/Mongood/releases

**Comment by MrWillCom** [comment]
> I released client package, you can try it: https://github.com/RenzHoly/Mongood/releases

I've tried this recently, this bug still occurs, the [record](https://github.com/RenzHoly/Mongood/files/5026400/record.zip).

**Comment by RenzHoly** [comment]
🤯

**Comment by RenzHoly** [comment]
Dose this bug happens on the other databases?

**Comment by MrWillCom** [comment]
No, it's really weird, the [record](https://github.com/RenzHoly/Mongood/files/5027649/record.zip).

Still tesing...

**Comment by MrWillCom** [comment]
Not just in the same database, the [record](https://github.com/RenzHoly/Mongood/files/5027699/record.zip).

**Comment by RenzHoly** [comment]
Can you export the data from `transmitter` database? I think this bug is caused by some special data

**Comment by MrWillCom** [comment]
The [export](https://github.com/RenzHoly/Mongood/files/5028318/export.zip).

**Comment by MrWillCom** [comment]
> May you export the data from `transmitter` database? I think this bug is caused by some special data

That database is called "transmister", the database that my project [transmister/transmister-server-and-web](https://github.com/transmister/transmister-server-and-web) uses.

**Comment by RenzHoly** [comment]
Thanks a lot! I found it is caused by the `key` field.
2 documents has the same value of `key` field.
I'll fix this very soon.

**Comment by MrWillCom** [comment]
> Thanks a lot! I found it is caused by the `key` field.
> 2 documents has the same value of `key` field.
> I'll fix this very soon.

I've tested, this bug occurs both when the `key` is different and the same.

The key is the keys of RSA encryption between server and the clients, and they are not the same, so it is propably not the reason.

**Comment by RenzHoly** [comment]
Fluent UI's [DetailsList](https://developer.microsoft.com/en-us/fluentui/#/controls/web/detailslist) component uses the key as React list item's key prop

I think that is a bug of DetailsList

The value of key is an object, so the component call `.toString()` and got `'[object Object]'`, then React renders wrong list item

**Comment by RenzHoly** [comment]
fixed: https://github.com/RenzHoly/Mongood/commit/8539e7c9b58908f1c06261c4cda1521c3e38d81b

**Comment by RenzHoly** [comment]
released: https://github.com/RenzHoly/Mongood/releases/tag/v0.1.1

**Comment by MrWillCom** [comment]
I'm now testing.

**Comment by MrWillCom** [comment]
Done!This bug is fixed!
